In [1]:
import numpy as np

Creating Arrays and inspecting your arrays

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [24]:
a.shape

(3,)

In [25]:
len(a)

3

In [26]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float )
b

2

In [29]:
b.ndim

2

In [33]:
b.dtype

dtype('float64')

In [34]:
b.dtype.name

'float64'

In [35]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype=float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [12]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [15]:
d = np.arange(10, 25, 5)
d

array([10, 15, 20])

In [16]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
e = np.full((2, 2), 7)
e

array([[7, 7],
       [7, 7]])

In [32]:
e.size

4

In [19]:
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [20]:
np.random.random((2, 2))

array([[0.4920007 , 0.62861162],
       [0.30772224, 0.54120616]])

In [23]:
np.empty((3, 2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

Asking for help

In [36]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


Array Mathematics


Arithmetic Operations

In [38]:
g = a - b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [39]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [40]:
b + a

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [42]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [43]:
a/b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [44]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [45]:
a * b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [46]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [48]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [47]:
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [49]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [50]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [51]:
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [52]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [53]:
e

array([[7, 7],
       [7, 7]])

In [54]:
f

array([[1., 0.],
       [0., 1.]])

In [55]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

Comparison

In [56]:
a == b

array([[False,  True,  True],
       [False, False, False]])

In [57]:
a

array([1, 2, 3])

In [58]:
a < 2

array([ True, False, False])

Aggregate Functions

In [59]:
a.sum()

6

In [60]:
a.min()

1

In [61]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [64]:
b.max(axis=0)

array([4., 5., 6.])

In [67]:
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [68]:
a

array([1, 2, 3])

In [69]:
a.mean()

2.0

In [72]:
np.std(b)

1.5920810978785667

Copying Arrays

In [74]:
h = a.view()
h

array([1, 2, 3])

In [75]:
np.copy(a)

array([1, 2, 3])

In [76]:
h = a.copy()

Sorting Arrays

In [77]:
a.sort()

In [78]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [83]:
c.sort(axis=2)

In [84]:
c

array([[[1. , 1.5, 2. ],
        [4. , 5. , 6. ]],

       [[2. , 3. , 3. ],
        [4. , 5. , 6. ]]])

Subsetting, Slicing, Indexing

Subsetting

In [85]:
a

array([1, 2, 3])

In [86]:
a[2]

3

In [87]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [88]:
b[1,2]

6.0

Slicing

In [89]:
a[0:2]

array([1, 2])

In [90]:
b[0:2, 1]

array([2., 5.])

In [91]:
b[0:2, 0:2]

array([[1.5, 2. ],
       [4. , 5. ]])

In [92]:
b[:1]

array([[1.5, 2. , 3. ]])

In [93]:
c

array([[[1. , 1.5, 2. ],
        [4. , 5. , 6. ]],

       [[2. , 3. , 3. ],
        [4. , 5. , 6. ]]])

In [94]:
c[1,...]

array([[2., 3., 3.],
       [4., 5., 6.]])

In [95]:
c[1,:,:]

array([[2., 3., 3.],
       [4., 5., 6.]])

In [97]:
a[::-1]

array([3, 2, 1])

Boolean Indexing

In [102]:
a[a<2]

array([1])

In [103]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [104]:
b[b<2]

array([1.5])

In [106]:
b[b<5]

array([1.5, 2. , 3. , 4. ])

Fancy Indexing

In [108]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [107]:
b[[1,0,1,0],
  [0,1,2,0]]

array([4. , 2. , 6. , 1.5])

In [112]:
b[[1,0,1,0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

Array manipulation

Transposing Array

In [115]:
i = np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [116]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [117]:
c

array([[[1. , 1.5, 2. ],
        [4. , 5. , 6. ]],

       [[2. , 3. , 3. ],
        [4. , 5. , 6. ]]])

In [118]:
c.T

array([[[1. , 2. ],
        [4. , 4. ]],

       [[1.5, 3. ],
        [5. , 5. ]],

       [[2. , 3. ],
        [6. , 6. ]]])

In [119]:
print(c.shape)
print(c.T.shape)

(2, 2, 3)
(3, 2, 2)


Changing Array Shape

In [120]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [122]:
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [123]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [124]:
g.reshape(3, -2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

Adding/Removing Elements

In [125]:
h

array([1, 2, 3])

In [128]:
np.resize(h, (2,6))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [129]:
np.append(h,g)

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [130]:
np.insert(a, 1, 5)

array([1, 5, 2, 3])

In [134]:
np.delete(a,[1])

array([1, 3])

Combining Arrays